version : '3.8'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  nginx:
      image: reversproxy
      ports:
        - 8000:80
#  nodejs:
#    image: node:16-alpine
#    container_name: nodejs_app
#    volumes:
#      - ./nodejs:/usr/src/app
#    working_dir: /usr/src/app
#    environment:
#      - NODE_ENV=development
#    command: npm start
#    ports:
#      - 3000:3000
#    depends_on:
#      - mongo
#  vue-ui:
#    build:
#      dockerfile: Dockerfile-dev
#    ports:
#      - "8080:8080"
#    container_name: vue-ui
volumes:
    db_data:
networks:
    wp_network: